-- DROP TABLE IF EXISTS currency
CREATE TABLE IF NOT EXISTS currency
(
    id   SERIAL NOT NULL PRIMARY KEY ,
    name VARCHAR(200) NOT NULL ,
    code VARCHAR(10) NOT NULL ,
    symbol VARCHAR(5)  NOT NULL
);

-- CREATE SEQUENCE JPA_SEQUENCE START WITH 3 INCREMENT BY 1 ;